# Generated by Django 3.0.8 on 2020-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200719_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Names',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
